### ISSUE TITLE
IndexError when selecting a folder with no music and peculiar behavior of Scale 

### ISSUE THREAD

**Issue by PRITHVIRAJ54** [warrior-guys/music-player#8]
Whenever I select any folder with no music, it throws `IndexError` and after I return to the previous directory, the music plays but the `Scale` widget does not function at all.  

![image](https://user-images.githubusercontent.com/101443246/160318234-d68106e1-5f02-4ddd-86e4-61bbac6d96ce.png)

**Desktop:**
 - OS: Windows 7
 - Browser: Chrome
 - Version: v1.1.1

**Comment by a2ys** [comment]
This bug has been fixed, and the fixed version along with other changes will be available in the next few days.
